name: "Check Spelling"

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

env:
  PYTHON_VERSION: "3.13"

jobs:
  check-spelling:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-latest"
    steps:
    - name: "setup python"
      uses: "KyoriPowered/.github/.github/actions/setup-python-env@trunk"
      with:
        runtime_version: "${{ env.PYTHON_VERSION }}"
        activate_venv: true
    - name: "setup python / spelling problem matcher"
      run: |
        echo "::add-matcher::.github/sphinx-spelling-matcher.json"
    - name: "run spellcheck"
      run: "make spelling"

